import type { NextPage } from 'next';
import Head from 'next/head';
// import styles from '../styles/Home.module.css';
import styles from '../../styles/Home.module.css';
import HomePage from './home';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>justinjohnson-dev-portfolio</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      {/* <HomePage /> */}
    </div>
  );
};

export default Home;
