import Head from 'next/head';
import HomePage from '../components/Home';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>justinjohnson-dev-portfolio</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <HomePage />
    </div>
  );
}
